export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  USAGE_NOT_FOUND: "USAGE_NOT_FOUND",
  USAGE_STATUS_CONFLICT: "USAGE_STATUS_CONFLICT",
  PART_STOCK_INSUFFICIENT: "PART_STOCK_INSUFFICIENT",
  TICKET_NOT_FOUND: "TICKET_NOT_FOUND",
  RESTORE_PENDING_PARTS: "RESTORE_PENDING_PARTS"
} as const;
