export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  SPARE_PART_PENDING: "SPARE_PART_PENDING",
  SPARE_PART_STOCK_INSUFFICIENT: "SPARE_PART_STOCK_INSUFFICIENT",
  SPARE_PART_USAGE_NOT_FOUND: "SPARE_PART_USAGE_NOT_FOUND",
  SPARE_PART_USAGE_STATUS_CONFLICT: "SPARE_PART_USAGE_STATUS_CONFLICT",
  REPAIR_TICKET_NOT_FOUND: "REPAIR_TICKET_NOT_FOUND"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
